// Student dashboard with skills, projects, team details, and AI-style skill-gap analysis.
import { useEffect, useState } from 'react';
import DashboardLayout from '../../layouts/DashboardLayout';
import ProfileCard from '../../components/student/ProfileCard';
import SkillCard from '../../components/student/SkillCard';
import ProjectCard from '../../components/student/ProjectCard';
import TeamCard from '../../components/student/TeamCard';
import SkillGapAudit from '../../components/student/SkillGapAudit';
import { analyzeSkillGap, recommendTeam } from '../../services/aiMatchingService';

const student={name:'Priya Sharma',initials:'PS',id:'STU-2026-048',department:'Computer Science',year:'Final Year',email:'priya.sharma@university.edu',completion:82};
const initialSkills=[{name:'React',category:'Frontend',level:'Advanced'},{name:'Node.js',category:'Backend',level:'Intermediate'},{name:'Figma',category:'Design',level:'Beginner'}];
const projects=[{title:'Smart Campus Navigator',category:'Mobile Application',description:'Help students find rooms, services, and events around campus.',skills:['React','UI/UX','APIs'],membersNeeded:2}];
const team={name:'Team Innovators',project:'Campus Capstone Matchmaker',members:[{name:'Priya Sharma',role:'Frontend Developer',initials:'PS'},{name:'Daniel Lee',role:'Backend Developer',initials:'DL'},{name:'Aisha Khan',role:'UI/UX Designer',initials:'AK'}]};
function StudentDashboard(){const[skills,setSkills]=useState(initialSkills);const[notice,setNotice]=useState('');const[analysis,setAnalysis]=useState(null);const[recommendations,setRecommendations]=useState([]);useEffect(()=>{async function loadAI(){const current=initialSkills.map(item=>item.name);setAnalysis(await analyzeSkillGap(current,['React','Node.js','MySQL','UI/UX']));setRecommendations(await recommendTeam(current,[{name:'Daniel Lee',role:'Backend Developer',skills:['Node.js','MySQL']},{name:'Aisha Khan',role:'UI/UX Designer',skills:['UI/UX','Research']}]))}loadAI()},[]);return <DashboardLayout><main className="student-page"><div className="student-page-heading"><div><h1>My Student Dashboard</h1><p>Track your skills, projects, and team progress.</p></div></div>{notice&&<div className="alert alert-success">{notice}</div>}<ProfileCard student={student}/><div className="row g-4 mt-1"><div className="col-xl-7"><section className="student-panel"><div className="student-panel-heading"><div><h2>My Skills</h2><p>Keep your strengths up to date.</p></div><button className="btn btn-primary btn-sm" onClick={()=>setSkills([...skills,{name:'Git',category:'Tools',level:'Intermediate'}])}><i className="bi bi-plus-lg"/> Add Skill</button></div><div className="skills-list">{skills.map(skill=><SkillCard key={skill.name} skill={skill} onRemove={name=>setSkills(skills.filter(item=>item.name!==name))}/>)}</div></section></div><div className="col-xl-5"><TeamCard team={team}/></div></div><section className="mt-4">{analysis?<SkillGapAudit analysis={analysis} recommendations={recommendations}/>:<div className="student-panel text-center">Analyzing your skills...</div>}</section><section className="student-panel mt-4"><div className="student-panel-heading"><div><h2>Available Projects</h2><p>Discover projects that match your skills.</p></div></div><div className="student-project-grid">{projects.map(project=><ProjectCard key={project.title} project={project} onApply={title=>setNotice(`Your application for ${title} has been saved.`)}/>)}</div></section></main></DashboardLayout>};export default StudentDashboard;
